// tslint:disable-next-line: no-unused-expression
export const TestData = [
  { id: 0, name: 'ID', selected: false },
  { id: 1, name: 'First', selected: false },
  { id: 2, name: 'Second', selected: false },
  { id: 3, name: 'Third', selected: false },
  { id: 4, name: 'Forth', selected: false },
  { id: 5, name: 'Fifth', selected: false },
];
export const Directors = [
  { id: 1, name: 'Alfonso_Cuaron', selected: false },
  { id: 2, name: 'James_Cameron', selected: false },
  { id: 3, name: 'Auguste_and_Louis_Lumiere', selected: false },
  { id: 4, name: 'Bong_Joon-ho', selected: false },
  { id: 5, name: 'Tim_Burton', selected: false },
  { id: 6, name: 'Stanley_Kubrick', selected: false },
  { id: 7, name: 'Martin_Scorsese', selected: false },
  { id: 8, name: 'Federico_Fellini', selected: false },
  { id: 9, name: 'Akira_Kurosawa', selected: false },
  { id: 10, name: 'Alfred_Hitchcock', selected: false },
  { id: 11, name: 'Charlie_Chaplin', selected: false },
  { id: 12, name: 'Steven_Spielberg', selected: false },
  { id: 13, name: 'Francis_Ford_Coppola', selected: false },
  { id: 14, name: 'Ingmar_Bergman', selected: false },
  { id: 15, name: 'David_Lean', selected: false },
];
// export const Directors = [
//   'Alfonso_Cuaron',
//   'James_Cameron',
//   'Auguste_and_Louis_Lumiere',
//   'Bong_Joon-ho',
//   'Tim_Burton',
//   'Stanley_Kubrick',
//   'Martin_Scorsese',
//   'Federico_Fellini',
//   'Akira_Kurosawa',
//   'Alfred_Hitchcock',
//   'Charlie_Chaplin',
//   'Steven_Spielberg',
//   'Francis_Ford_Coppola',
//   'Ingmar_Bergman',
//   'David_Lean',
// ];
